/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author Alexander
 */
public class LoginScreen extends javax.swing.JFrame {

    // Para pegar a posição do ponteiro do mouse ao clicar e arrastar a tela de login
    public int xMouse;
    public int yMouse;

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();

        loginUserInput.setFocusable(true);
        loginUserInput.grabFocus();
        loginPasswordInput.setFocusable(true);
        loginPasswordInput.grabFocus();

        loginButton.grabFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        imgPanel = new javax.swing.JPanel();
        bgLogin = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        registerUserInput = new javax.swing.JTextField();
        registerEmailInput = new javax.swing.JTextField();
        registerNameInput = new javax.swing.JTextField();
        registerPasswordInput = new javax.swing.JPasswordField();
        registerConfirmPasswordInput = new javax.swing.JPasswordField();
        registerButton = new javax.swing.JButton();
        registerLoginButton = new javax.swing.JButton();
        loginPanel = new javax.swing.JPanel();
        loginIcon = new javax.swing.JLabel();
        loginUserInput = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        labelNotHaveAcc = new javax.swing.JLabel();
        labelRegister = new javax.swing.JLabel();
        labelExit = new javax.swing.JLabel();
        loginPasswordInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(920, 450));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));

        imgPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                imgPanelMouseDragged(evt);
            }
        });
        imgPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                imgPanelMousePressed(evt);
            }
        });

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bg_login.jpg"))); // NOI18N

        javax.swing.GroupLayout imgPanelLayout = new javax.swing.GroupLayout(imgPanel);
        imgPanel.setLayout(imgPanelLayout);
        imgPanelLayout.setHorizontalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgLogin)
        );
        imgPanelLayout.setVerticalGroup(
            imgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imgPanelLayout.createSequentialGroup()
                .addComponent(bgLogin)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        formPanel.setBackground(new java.awt.Color(255, 255, 255));
        formPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerPanel.setVisible(false);

        registerUserInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        registerUserInput.setForeground(new java.awt.Color(153, 153, 153));
        registerUserInput.setText("Usuário...");
        registerUserInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        registerUserInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerUserInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerUserInputFocusLost(evt);
            }
        });

        registerEmailInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        registerEmailInput.setForeground(new java.awt.Color(153, 153, 153));
        registerEmailInput.setText("Email...");
        registerEmailInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        registerEmailInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerEmailInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerEmailInputFocusLost(evt);
            }
        });

        registerNameInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        registerNameInput.setForeground(new java.awt.Color(153, 153, 153));
        registerNameInput.setText("Nome...");
        registerNameInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        registerNameInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerNameInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerNameInputFocusLost(evt);
            }
        });

        registerPasswordInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        registerPasswordInput.setForeground(new java.awt.Color(153, 153, 153));
        registerPasswordInput.setText("Senha...");
        registerPasswordInput.setEchoChar('\u0000');
        registerPasswordInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        registerPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerPasswordInputFocusLost(evt);
            }
        });

        registerConfirmPasswordInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        registerConfirmPasswordInput.setForeground(new java.awt.Color(153, 153, 153));
        registerConfirmPasswordInput.setText("Confirmar senha...");
        registerConfirmPasswordInput.setEchoChar('\u0000');
        registerConfirmPasswordInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        registerConfirmPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                registerConfirmPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                registerConfirmPasswordInputFocusLost(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(0, 153, 204));
        registerButton.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Cadastrar");
        registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });

        registerLoginButton.setBackground(new java.awt.Color(255, 255, 255));
        registerLoginButton.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        registerLoginButton.setForeground(new java.awt.Color(0, 153, 204));
        registerLoginButton.setText("Entrar");
        registerLoginButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 204), 1, true));
        registerLoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerLoginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout registerPanelLayout = new javax.swing.GroupLayout(registerPanel);
        registerPanel.setLayout(registerPanelLayout);
        registerPanelLayout.setHorizontalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerUserInput)
                    .addComponent(registerEmailInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(registerNameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(registerPasswordInput)
                    .addComponent(registerConfirmPasswordInput)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(registerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        registerPanelLayout.setVerticalGroup(
            registerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(registerUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registerConfirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        formPanel.add(registerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 450));

        loginPanel.setBackground(new java.awt.Color(255, 255, 255));

        loginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        loginUserInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        loginUserInput.setForeground(new java.awt.Color(153, 153, 153));
        loginUserInput.setText("Usuário...");
        loginUserInput.setToolTipText("");
        loginUserInput.setFocusable(false);
        loginUserInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        loginUserInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginUserInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginUserInputFocusLost(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(0, 153, 204));
        loginButton.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Entrar");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        labelNotHaveAcc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        labelNotHaveAcc.setForeground(new java.awt.Color(79, 79, 79));
        labelNotHaveAcc.setText("Não possui uma conta?");

        labelRegister.setText("<html>\n<a href = \"#\"> Cadastrar </a>\n</html>");
        labelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisterMouseClicked(evt);
            }
        });

        labelExit.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 36)); // NOI18N
        labelExit.setForeground(new java.awt.Color(0, 153, 204));
        labelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelExit.setText("x");
        labelExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        loginPasswordInput.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        loginPasswordInput.setForeground(new java.awt.Color(153, 153, 153));
        loginPasswordInput.setText("Senha...");
        loginPasswordInput.setEchoChar('\u0000');
        loginPasswordInput.setFocusable(false);
        loginPasswordInput.setMargin(new java.awt.Insets(2, 10, 2, 2));
        loginPasswordInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginPasswordInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginPasswordInputFocusLost(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loginUserInput)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addComponent(labelNotHaveAcc)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNotHaveAcc)
                    .addComponent(labelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginUserInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(loginPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formPanel.add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(imgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisterMouseClicked
        loginPanel.setVisible(false);
        registerPanel.setVisible(true);
    }//GEN-LAST:event_labelRegisterMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_labelExitMouseClicked

    private void imgPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_imgPanelMousePressed

    private void imgPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_imgPanelMouseDragged

    private void loginUserInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserInputFocusGained
        inputFocusGained(loginUserInput, null, "Usuário...");
    }//GEN-LAST:event_loginUserInputFocusGained

    private void loginUserInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginUserInputFocusLost
        inputFocusLost(loginUserInput, null, "Usuário...");
    }//GEN-LAST:event_loginUserInputFocusLost

    private void loginPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordInputFocusGained
        inputFocusGained(null, loginPasswordInput, "Senha...");
    }//GEN-LAST:event_loginPasswordInputFocusGained

    private void loginPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginPasswordInputFocusLost
        inputFocusLost(null, loginPasswordInput, "Senha...");
    }//GEN-LAST:event_loginPasswordInputFocusLost

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        new HomeScreen().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_loginButtonMouseClicked

    private void registerLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerLoginButtonMouseClicked
        registerPanel.setVisible(false);
        loginPanel.setVisible(true);
    }//GEN-LAST:event_registerLoginButtonMouseClicked

    private void registerUserInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserInputFocusGained
        inputFocusGained(registerUserInput, null, "Usuário...");
    }//GEN-LAST:event_registerUserInputFocusGained

    private void registerUserInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerUserInputFocusLost
        inputFocusLost(registerUserInput, null, "Usuário...");
    }//GEN-LAST:event_registerUserInputFocusLost

    private void registerEmailInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerEmailInputFocusGained
        inputFocusGained(registerEmailInput, null, "Email...");
    }//GEN-LAST:event_registerEmailInputFocusGained

    private void registerEmailInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerEmailInputFocusLost
        inputFocusLost(registerEmailInput, null, "Email...");
    }//GEN-LAST:event_registerEmailInputFocusLost

    private void registerNameInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerNameInputFocusGained
        inputFocusGained(registerNameInput, null, "Nome...");
    }//GEN-LAST:event_registerNameInputFocusGained

    private void registerNameInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerNameInputFocusLost
        inputFocusLost(registerNameInput, null, "Nome...");
    }//GEN-LAST:event_registerNameInputFocusLost

    private void registerPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordInputFocusGained
        inputFocusGained(null, registerPasswordInput, "Senha...");
    }//GEN-LAST:event_registerPasswordInputFocusGained

    private void registerPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerPasswordInputFocusLost
        inputFocusLost(null, registerPasswordInput, "Senha...");
    }//GEN-LAST:event_registerPasswordInputFocusLost

    private void registerConfirmPasswordInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerConfirmPasswordInputFocusGained
        inputFocusGained(null, registerConfirmPasswordInput, "Confirmar senha...");
    }//GEN-LAST:event_registerConfirmPasswordInputFocusGained

    private void registerConfirmPasswordInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_registerConfirmPasswordInputFocusLost
        inputFocusLost(null, registerConfirmPasswordInput, "Confirmar senha...");
    }//GEN-LAST:event_registerConfirmPasswordInputFocusLost

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked

    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLogin;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel imgPanel;
    private javax.swing.JLabel labelExit;
    private javax.swing.JLabel labelNotHaveAcc;
    private javax.swing.JLabel labelRegister;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPasswordField loginPasswordInput;
    private javax.swing.JTextField loginUserInput;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPasswordField registerConfirmPasswordInput;
    private javax.swing.JTextField registerEmailInput;
    private javax.swing.JButton registerLoginButton;
    private javax.swing.JTextField registerNameInput;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPasswordField registerPasswordInput;
    private javax.swing.JTextField registerUserInput;
    // End of variables declaration//GEN-END:variables

    private void inputFocusGained(JTextField textInput, JPasswordField passwordInput, String text) {
        if (textInput != null) {
            if (textInput.getText().equals(text)) {
                textInput.setText("");
                textInput.setForeground(new Color(79, 79, 79));
            }
        } else {
            if (passwordInput.getText().equals(text)) {
                passwordInput.setText("");
                passwordInput.setEchoChar('\u2022');
                passwordInput.setForeground(new Color(79, 79, 79));
            }
        }
    }

    private void inputFocusLost(JTextField textInput, JPasswordField passwordInput, String text) {
        if (textInput != null) {
            if (textInput.getText().isEmpty()) {
                textInput.setText(text);
                textInput.setForeground(new Color(153, 153, 153));
            }
        } else {
            if (passwordInput.getText().isEmpty()) {
                passwordInput.setText(text);
                passwordInput.setEchoChar('\u0000');
                passwordInput.setForeground(new Color(153, 153, 153));
            }
        }
    }
}
