/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.border.EmptyBorder;
import model.Store;
import util.RendererStoreList;

/**
 *
 * @author Alexander
 */
public class Stores extends javax.swing.JInternalFrame {

    public ArrayList<Store> listItems = new ArrayList<>();
    private JList<Store> storeList = new JList<Store>();
    private DefaultListModel<Store> model = new DefaultListModel<>();

    /**
     * Creates new form StoreScreen
     */
    public Stores() {
        initComponents();

        this.renderList();
    }

    private void renderList() {
        storeList = new javax.swing.JList<>();
        storeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                storeListValueChanged(evt);
            }
        });

        storeList.setModel(model);
        storeList.setCellRenderer(new RendererStoreList());
        storeList.setBackground(new Color(255, 255, 255));
        storeList.setBorder(new EmptyBorder(10, 10, 10, 10));
        storeList.setLayoutOrientation(JList.HORIZONTAL_WRAP);
        storeList.setVisibleRowCount(-1);
        //storeList.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        //model.addElement(new Store("add", "add", "add", "add", "add", "add", "add", "add"));

        storePanel.add(new JScrollPane(storeList));
        storePanel.setBorder(new EmptyBorder(10, 10, 10, 10));

        // Testando
        Store store1 = new Store("28.245.139/0001-14", "Swerts Store", "", "", "", "", "", "");
        Store store2 = new Store("28.245.139/0001-14", "Central Modas", "", "", "", "", "", "");
        Store store3 = new Store("28.245.139/0001-14", "Chose Eletronics", "", "", "", "", "", "");
        listItems.add(store1);
        listItems.add(store2);
        listItems.add(store3);

        for (Store elementoDaLista : listItems) {
            model.addElement(elementoDaLista);
        }
        storePanel.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        storePanel.setBackground(new java.awt.Color(255, 255, 255));
        storePanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(storePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(storePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void storeListValueChanged(javax.swing.event.ListSelectionEvent evt) {
        Store aux = storeList.getSelectedValue();
        System.out.println(aux.getName());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel storePanel;
    // End of variables declaration//GEN-END:variables
}
